version: "3.9"
services:
  server1:
    build:
      context: .
      dockerfile: ./DockerFile_Builders/Server/Dockerfile
    ports:
      - "8020:8080"
  server2:
    build:
      context: .
      dockerfile: ./DockerFile_Builders/Server/Dockerfile
    ports:
      - "8021:8080"
 rabbitmq:
   image: "rabbitmq:3-management"
   ports:
     - "5672:5672"
     - "15672:15672"
