version: "3.9"
services:

  server:
    build:
      context: .
      dockerfile: ./DockerFile_Builders/Server/Dockerfile
    ports:
      - "8021:8080"

  rabbitmq_server: # login guest:guest
    image: rabbitmq:3-management
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
  rabbitmq_queues:
    depends_on:
      - "rabbitmq_server"
    links:
      - "rabbitmq_server"
    environment:
      - HOSTNAMERABBIT=rabbitmq_server
    restart: on-failure
    
    build:
      context: .
      dockerfile: DockerFile_Builders/RabbitMQ/Dockerfile

  user_service:
    depends_on:
      - "rabbitmq_queues"
    links:
      - "rabbitmq_queues"
    build:
      context: .
      dockerfile: DockerFile_Builders/Services/User/Dockerfile
  moderator_service:
    depends_on:
      - "rabbitmq_queues"
    links:
      - "rabbitmq_queues"
    build:
      context: .
      dockerfile: DockerFile_Builders/Services/Moderator/Dockerfile
  user_to_user_service:
    depends_on:
      - "rabbitmq_queues"
    links:
      - "rabbitmq_queues"
    build:
      context: .
      dockerfile: DockerFile_Builders/Services/UserToUser/Dockerfile
  chat_service:
    depends_on:
      - "rabbitmq_queues"
    links:
      - "rabbitmq_queues"
    build:
      context: .
      dockerfile: DockerFile_Builders/Services/Chat/Dockerfile
