version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: ./DockerFile_Builders/Server/Dockerfile
    ports:
      - "8020:8081"
#  rabbitmq:
#    image: "rabbitmq:3-management"
#    ports:
#      - "5672:5672"
#      - "15672:15672"