# Load tests the user to user service ONLY
# Load tests the user service ONLY
config:
  target: 'http://localhost:8021'
  phases:
    - duration: 2
      arrivalRate: 10
before:
 flow:
  - post:
        url: "/ss"
        json:
          userData:
                email: "ariannagrande@gmail.com"
                password: "12345678"
          command: "SignIn"
          application: "User"
        capture:
          json: "$.token"
          as: "userToken"


  

scenarios:
  - name: "Create Block"
    flow:
    - post:
        url: "/ss"
        json:
          blockData:
                source_user_id: 1
                target_user_id: 2
                created_at: "11-11-1998"
          command: "CreateBlock"
          application: "UserToUser"
        headers:
         authorization: "{{ userToken }}"
  # UNCOMMENT WHEN FIXED
  # - name: "Get Matches"
  #   flow:
  #   - post:
  #       url: "/ss"
  #       json:
  #        userData:
  #           id: 1
  #        command: "GetMatches"
  #        application: "User"
  #       headers:
  #        authorization: "{{ userToken }}"

 
  - name: "Get All Profile Views"
    flow:
    - post:
        url: "/ss"
        json:
         page: 0
         limit: 5
         command: "GetAllProfileViews"
         application: "UserToUser"
        headers:
         authorization: "{{ userToken }}"
  

  # UNCOMMENT WHEN FIXED
  # - name: "Get All Interactions"
  #   flow:
  #   - post:
  #       url: "/ss"
  #       json:
  #        page: 0
  #        limit: 1 
  #        command: "GetAllInteractions"
  #        application: "User"
  #       headers:
  #        authorization: "{{ userToken }}"

  - name: "Get Chat"
    flow:
    - post:
        url: "/ss"
        json:
         chatData:
          id: 1
         command: "GetChat"
         application: "Chat"
        headers:
         authorization: "{{ userToken }}"

  
         
  
  