name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: cd Backend && docker-compose up -d
      - name: Test
        run: docker exec -it backend_server mvn test
